export const areaOffices = [
  { name: 'barnawa' },
  { name: 'kawo' },
  { name: 'jaji' },
  { name: 'doka' },
  { name: 'mando' },
  { name: 'rigasa' },
  { name: 'tudun wada' },
  { name: 'new millenium city' },
  { name: 'zaria city' },
  { name: 'samaru' },
  { name: 'sabon gari' },
  { name: 'kebbi north' },
  { name: 'kebbi south' },
  { name: 'kebbi central' },
  { name: 'kebbi east' },
  { name: 'sokoto north' },
  { name: 'sokoto central' },
  { name: 'sokoto south' },
  { name: 'talata mafara' },
  { name: 'gusau' },
  { name: 'kafanchan' },
  { name: 'makera' },
];
